# Generated by Django 5.2.15 on 2026-08-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companymap', '0005_company_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('session_type', models.CharField(choices=[('keynote', 'Keynote'), ('panel', 'Panel Discussion'), ('workshop', 'Workshop'), ('networking', 'Networking'), ('meal', 'Meal / Social'), ('logistics', 'Logistics'), ('exhibitor_presentation', 'Exhibitor Presentation'), ('other', 'Other')], default='other', max_length=24)),
                ('day', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('raw_time_label', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('speakers', models.JSONField(blank=True, default=list, help_text='List of {name, affiliation} dicts.')),
                ('company_name', models.CharField(blank=True, help_text='Presenting company, for exhibitor-presentation sessions.', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=64)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='conferences.conference')),
            ],
            options={
                'ordering': ['day', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conferences.conference')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of ConferenceCompany.Tag values.')),
                ('booth', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Optional link to the matching company in the main map database.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_appearances', to='companymap.company')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='conferences.conference')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('conference', 'name'), name='unique_company_per_conference')],
            },
        ),
    ]
