# Generated by Django 5.2.15 on 2026-08-25 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companymap', '0004_alter_company_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactdb_list_items', to='companymap.company')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contactdb.companylist')),
            ],
            options={
                'ordering': ['company__name'],
            },
        ),
        migrations.AddField(
            model_name='companylist',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='contactdb_lists', through='contactdb.CompanyListItem', to='companymap.company'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('linkedin_url', models.URLField(blank=True)),
                ('company_name', models.CharField(blank=True, help_text="Free-text company name, used when there's no matching Company record.", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactdb_people', to='companymap.company')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contactdb.personlist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='contactdb.person')),
            ],
            options={
                'ordering': ['person__name'],
            },
        ),
        migrations.AddField(
            model_name='personlist',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='lists', through='contactdb.PersonListItem', to='contactdb.person'),
        ),
        migrations.AddConstraint(
            model_name='companylistitem',
            constraint=models.UniqueConstraint(fields=('list', 'company'), name='unique_company_per_list'),
        ),
        migrations.AddConstraint(
            model_name='personlistitem',
            constraint=models.UniqueConstraint(fields=('list', 'person'), name='unique_person_per_list'),
        ),
    ]
