# Generated by Django 5.2.15 on 2026-08-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prior_connections',
            field=models.JSONField(blank=True, default=list, help_text='Names of the warm-connection network(s) this person belongs to.'),
        ),
        migrations.AddField(
            model_name='person',
            name='segment',
            field=models.CharField(blank=True, choices=[('cdmo', 'CDMO'), ('cro', 'CRO'), ('reagents', 'Reagents & Lab Tools'), ('equipment', 'Equipment & Devices'), ('pharma', 'Pharma / Biotech'), ('consulting', 'Consulting & BD'), ('non_pharma', 'Non-Pharma')], max_length=16),
        ),
    ]
