# Generated by Django 5.2.15 on 2026-08-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0005_company_modality'),
        ('contactdb', '0002_person_prior_connections_person_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('founded', models.CharField(blank=True, max_length=64)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('employee_count', models.CharField(blank=True, max_length=64)),
                ('ownership', models.CharField(blank=True, max_length=255)),
                ('global_presence', models.CharField(blank=True, max_length=255)),
                ('nature', models.TextField(blank=True)),
                ('service_model', models.TextField(blank=True)),
                ('client_profile', models.TextField(blank=True)),
                ('modality_focus', models.TextField(blank=True)),
                ('therapeutic_focus', models.TextField(blank=True)),
                ('trial_phase_preference', models.TextField(blank=True)),
                ('decision_makers', models.JSONField(blank=True, default=list, help_text='List of {name, title, note} dicts.')),
                ('latest_signals_period', models.CharField(blank=True, max_length=128)),
                ('latest_signals', models.JSONField(blank=True, default=list, help_text='List of bullet strings.')),
                ('opportunity_assessment', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of citation strings/URLs.')),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='companymap.company')),
            ],
            options={
                'verbose_name': 'company brief',
            },
        ),
    ]
