# Generated by Django 5.2.15 on 2026-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactdb', '0003_companybrief'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stakeholder_role',
            field=models.CharField(blank=True, choices=[('decision_maker', 'Decision Maker'), ('champion', 'Champion'), ('influencer', 'Influencer'), ('end_user', 'End User')], help_text='BD-adoption persona inferred from title: CxO/Chairman/Founder = decision maker, VP/Director in BD-Marketing-Data = champion, associate director/senior manager = influencer, manager/associate = end user.', max_length=16),
        ),
    ]
