# Generated by Django 5.2.15 on 2026-07-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(max_length=120)),
                ('state_code', models.CharField(max_length=2)),
                ('region', models.CharField(choices=[('west', 'West Coast'), ('east', 'East Coast'), ('other', 'Other')], default='other', max_length=12)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('funding_data', models.TextField(blank=True)),
                ('revenue_data', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['state_code', 'city', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city', 'state_code'), name='unique_company_city_state')],
            },
        ),
        migrations.CreateModel(
            name='DecisionMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_makers', to='companymap.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_decision_maker_per_company')],
            },
        ),
    ]
