# Generated by Django 5.2.15 on 2026-07-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0002_company_account_list_source_company_account_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
