# Generated by Django 5.2.15 on 2026-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0003_company_annual_revenue_company_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='product_category',
            field=models.TextField(blank=True),
        ),
    ]
