# Generated by Django 5.2.15 on 2026-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0004_alter_company_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='modality',
            field=models.CharField(blank=True, help_text='Comma-separated therapeutic modality focus, e.g. Small Molecules, Biologics, Cell Therapy.', max_length=255),
        ),
    ]
