# Generated by Django 5.2.15 on 2026-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0005_company_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='synthego_relation',
            field=models.CharField(blank=True, choices=[('competitor', 'Synthego Competitor'), ('adjacent', 'Synthego Adjacent'), ('partner', 'Synthego Partner'), ('no_relation', 'No Relation with Synthego')], help_text="How this company's business relates to Synthego's (CDMO/CRO/Reagents companies only).", max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='synthego_relation_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
