# Generated by Django 5.2.15 on 2026-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0006_company_synthego_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_data_bi_team',
            field=models.BooleanField(default=False, help_text="True if a known contact's department is Data Warehouse, Data Science, BI, Digital Transformation, or IT. Derived from existing Person records only."),
        ),
        migrations.AddField(
            model_name='company',
            name='has_marketing_presales_team',
            field=models.BooleanField(default=False, help_text="True if a known contact's department is Marketing, Business Development, Sales Engineering, or Demand Generation. Derived from existing Person records only."),
        ),
    ]
