# Generated by Django 5.2.15 on 2026-08-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0007_company_has_data_bi_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_company_id', models.CharField(blank=True, max_length=255)),
                ('post_url', models.URLField(max_length=1000, unique=True)),
                ('post_text', models.TextField(blank=True)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_posts', to='companymap.company')),
            ],
            options={
                'ordering': ['-post_date'],
                'indexes': [models.Index(fields=['company', '-post_date'], name='companymap__company_184743_idx'), models.Index(fields=['-post_date'], name='companymap__post_da_0a1480_idx')],
            },
        ),
    ]
