# Generated by Django 5.2.15 on 2026-08-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0008_companylinkedinpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylinkedinpost',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='companylinkedinpost',
            index=models.Index(fields=['is_saved'], name='companymap__is_save_880fa8_idx'),
        ),
    ]
