# Generated by Django 5.2.15 on 2026-08-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0009_companylinkedinpost_is_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylinkedinpost',
            name='ai_headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companylinkedinpost',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylinkedinpost',
            name='category',
            field=models.CharField(blank=True, choices=[('capability_expansion', 'Capability Expansion'), ('new_partnership', 'New Partnership'), ('new_funding', 'New Funding'), ('research_milestone', 'Research Milestone'), ('hiring', 'Hiring'), ('event_attendance', 'Event Attendance'), ('company_update', 'Company Update')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='companylinkedinpost',
            index=models.Index(fields=['category', '-post_date'], name='companymap__categor_ab848e_idx'),
        ),
    ]
