# Generated by Django 5.2.15 on 2026-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymap', '0010_companylinkedinpost_ai_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_on_map',
            field=models.BooleanField(default=True, help_text='Whether this company appears as a pin on the map. Buyer-side companies (pharma/biotech, drug developers) are kept in the database for reference but excluded from the map, which is scoped to supply-side vendors.'),
        ),
    ]
